<template>
  <div class="justify-center m-5 flex gap-3 text-sm text-gray-500 h-5 items-center pb-10">

    built using <a href="https://nuxtjs.com" target="_blank" class="i-logos-nuxt" />
    hosted on <a href="https://firebase.com" target="_blank" class="i-logos-firebase" />
    generated by <a href="https://github.com/lodaya" target="_blank" class="i-logos-github-icon" />
  </div>
</template>